version: "3.8"
services:
  flask-dev:
    build:
      context: ./docker/flask-dev
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./flask-dev
        target: /home/flask-dev/workdir
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.main.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=1
    user: flask-dev
    tty: true
    stdin_open: true
